export const codes: { [name: string]: string } = {
    'Saint Petersburg': 'RU-SPE',
    Moscow: 'RU-MOW',
    Sevastopol: 'RU-SEV',
    'Kaliningrad Oblast': 'RU-KGD',
    'Leningrad Oblast': 'RU-LEN',
    'Pskov Oblast': 'RU-PSK',
    'Smolensk Oblast': 'RU-SMO',
    'Bryansk Oblast': 'RU-BRY',
    'Republic of Crimea': 'RU-CR',
    'Karelia Republic': 'RU-KR',
    'Novgorod Oblast': 'RU-NGR',
    'Tver Oblast': 'RU-TVE',
    'Kaluga Oblast': 'RU-KLU',
    'Orel Oblast': 'RU-ORL',
    'Kursk Oblast': 'RU-KRS',
    'Adygea Republic': 'RU-AD',
    'Murmansk Oblast': 'RU-MUR',
    'Vologda Oblast': 'RU-VLG',
    'Yaroslavl Oblast': 'RU-YAR',
    'Moscow Oblast': 'RU-MOS',
    'Tula Oblast': 'RU-TUL',
    'Lipetsk Oblast': 'RU-LIP',
    'Belgorod Oblast': 'RU-BEL',
    'Krasnodar Krai': 'RU-KDA',
    'Karachay-Cherkess Republic': 'RU-KC',
    'Kabardino-Balkarian Republic': 'RU-KB',
    'Ivanovo Oblast': 'RU-IVA',
    'Vladimir Oblast': 'RU-VLA',
    'Ryazan Oblast': 'RU-RYA',
    'Tambov Oblast': 'RU-TAM',
    'Voronezh Oblast': 'RU-VOR',
    'Rostov Oblast': 'RU-ROS',
    'Stavropol Krai': 'RU-STA',
    'North Ossetia - Alania Republic': 'RU-SE',
    'Kostroma Oblast': 'RU-KOS',
    'Nizhny Novgorod Oblast': 'RU-NIZ',
    'Mordovia Republic': 'RU-MO',
    'Penza Oblast': 'RU-PNZ',
    'Volgograd Oblast': 'RU-VGG',
    'Kalmykia Republic': 'RU-KL',
    'Chechen Republic': 'RU-CE',
    'Ingushetia Republic': 'RU-IN',
    'Mari El Republic': 'RU-ME',
    'Chuvashia Republic': 'RU-CU',
    'Ulyanovsk Oblast': 'RU-ULY',
    'Saratov Oblast': 'RU-SAR',
    'Astrakhan Oblast': 'RU-AST',
    'Dagestan Republic': 'RU-DA',
    'Arkhangelsk Oblast': 'RU-ARK',
    'Kirov Oblast': 'RU-KIR',
    'Tatarstan Republic': 'RU-TT',
    'Samara Oblast': 'RU-SAM',
    'Orenburg Oblast': 'RU-ORE',
    'Nenets Autonomous Okrug': 'RU-NEN',
    'Komi Republic': 'RU-KO',
    'Perm Krai': 'RU-PER',
    'Udmurt Republic': 'RU-UD',
    'Bashkortostan Republic': 'RU-BA',
    'Yamalo-Nenets Autonomous Okrug': 'RU-YAN',
    'Khanty-Mansi Autonomous Okrug': 'RU-KHM',
    'Sverdlovsk Oblast': 'RU-SVE',
    'Chelyabinsk Oblast': 'RU-CHE',
    'Tyumen Oblast': 'RU-TYU',
    'Kurgan Oblast': 'RU-KGN',
    'Omsk Oblast': 'RU-OMS',
    'Tomsk Oblast': 'RU-TOM',
    'Novosibirsk Oblast': 'RU-NVS',
    'Altai Krai': 'RU-ALT',
    'Altai Republic': 'RU-GA',
    'Krasnoyarsk Krai': 'RU-KYA',
    'Kemerovo Oblast': 'RU-KEM',
    'Khakassia Republic': 'RU-KK',
    'Tyva Republic': 'RU-TY',
    'Irkutsk Oblast': 'RU-IRK',
    'Buryatia Republic': 'RU-BU',
    'Zabaykalsky Krai': 'RU-ZAB',
    'Sakha (Yakutiya) Republic': 'RU-SA',
    'Amur Oblast': 'RU-AMU',
    'Jewish Autonomous Okrug': 'RU-YEV',
    'Chukotka Autonomous Okrug': 'RU-CHU',
    'Magadan Oblast': 'RU-MAG',
    'Khabarovsk Krai': 'RU-KHA',
    'Primorsky Krai': 'RU-PRI',
    'Kamchatka Krai': 'RU-KAM',
    'Sakhalin Oblast': 'RU-SAK',
};
